name: Deploy to self-hosted runner
on:
  push:
    branches:
      - main
	pull_request:
		branches:
			- main
		paths:
			- '.github/workflows/deploy-runner.yml'
jobs:
  deploy:
    runs-on:
      - self-hosted
      - Shion-raspi-cm4
      - ARM64
      - Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build binary
        run: go build -o lumos-discord-bot .

      - name: Deploy binary
        run: |
          cp lumos-discord-bot /home/lumos-bot/lumos-discord-bot/lumos-discord-bot

      - name: Restart service
        run: |
        	# THIS COMMAND IS ALLOWED VIA /etc/sudoers.d/lumos-bot
        	sudo /bin/systemctl restart lumos-discord-bot.service
