name: Docker Build Image & publish to GHCR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/publish-image.yml'
jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return `ghcr.io/${context.repo.owner.toLowerCase()}/${context.repo.repo.toLowerCase()}`

      - name: Echo repository slug
        run: |
          echo "Repository slug: ${{ steps.repo_slug.outputs.result }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.repo_slug.outputs.result }}:latest
